[package]
name = "magicblock-delegation-program"
description = "Delegation program for the Ephemeral Rollups"
version = "1.1.3"
authors = ["Magicblock Labs <dev@magicblock.gg>"]
edition = "2021"
license = "MIT"
homepage = "https://www.magicblock.gg/"
documentation = "https://docs.magicblock.gg/"
repository = "https://github.com/magicblock-labs/delegation-program"
readme = "./README.md"
keywords = ["solana", "crypto", "delegation", "ephemeral-rollups", "magicblock"]

[profile.release]
opt-level  = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
debug = 0
incremental = false
overflow-checks = false

[lib]
crate-type = ["cdylib", "lib"]
name = "dlp"

[features]
no-entrypoint = []
sdk = ["no-entrypoint"]
program = [
  "dep:pinocchio",
  "dep:pinocchio-log",
  "dep:pinocchio-pubkey",
  "dep:pinocchio-system",
  "dep:rkyv",
  "dep:solana-curve25519",
]

# Default build = program path + security txt
default = [
    "program",
    "solana-security-txt",
]
unit_test_config = []
log-cost = []
logging = []

[dependencies]
borsh = { version = "1.5.3", features = [ "derive" ] }
solana-program = { version = ">=1.16, <3.0.0" }
bytemuck = { version = ">=1", features = [ "derive" ] }
num_enum = "^0.7.2"
thiserror = { version = ">=1" }
solana-security-txt = { version = ">=1.1", optional = true }
solana-curve25519 = { version = ">=2.2", optional = true }
bincode = { version = "^1.3" }
pinocchio-log = { version = "0.5.0", optional = true }
pinocchio = { version = "0.9.2", optional = true }
pinocchio-pubkey = { version = "0.3.0", optional = true }
pinocchio-system = { version = "0.3.0", optional = true }
rkyv = { version = "0.7.45", optional = true }
static_assertions = "1.1.0"
strum = { version = ">=0.27", features = ["derive"] }

[dev-dependencies]
rand = { version = "=0.8.5", features = ["small_rng"] }
solana-program-test = ">=1.16"
solana-sdk = ">=1.16"
tokio = { version = "^1.0", features = ["full"] }
magicblock-delegation-program = { path = ".", features = ["unit_test_config"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
